version: "3.9"

services:

  mlflow:
    build: ./mlflow
    container_name: mlflow
    networks:
      - app-network
    expose:
      - "5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://admin:password@postgres:5432/mlflow
      MLFLOW_DEFAULT_ARTIFACT_ROOT: minio://mlflow
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      - postgres
    restart: on-failure

  zenml:
    build: ./zenml
    container_name: zenml
    networks:
      - app-network
    expose:
      - "8080"
    environment:
      ZENML_STORE_URL: mysql://zenml_user:zenml_pass@mysql:3306/zenml
      ZENML_SERVER_AUTO_ACTIVATE: 1
      ZENML_DEFAULT_USER_NAME: admin
      ZENML_DEFAULT_USER_PASSWORD: password
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
  
  # MySQL is just for zenml :(  it doesnt support postgres and i dont wanna use mysql for anything else
  mysql:
    build: ./mysql
    container_name: mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
  
  postgres:
    build: ./postgres
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    expose:
      - "5432"
  minio:
    build: ./minio
    container_name: minio
    networks:
      - app-network
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=mlflow,zenml
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - zenml
      - mlflow
      - minio

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  airflow-init:
    image: apache/airflow:3.1.5
    container_name: airflow-init
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    environment: &airflow-env
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:password@postgres:5432/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:password@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
    volumes: &airflow-vols
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/config:/opt/airflow/config
    user: "${AIRFLOW_UID:-50000}:0"
    command: >
      bash -c "airflow db migrate"
    restart: "no"

  airflow-api-server:
    image: apache/airflow:3.1.5
    container_name: airflow-api-server
    networks:
      - app-network
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-env
    volumes: *airflow-vols
    user: "${AIRFLOW_UID:-50000}:0"
    ports:
      - "8082:8080"
    command: ["bash", "-c", "airflow api-server"]
    restart: on-failure

  airflow-scheduler:
    image: apache/airflow:3.1.5
    container_name: airflow-scheduler
    networks:
      - app-network
    depends_on:
      airflow-api-server:
        condition: service_started
    environment: *airflow-env
    volumes: *airflow-vols
    user: "${AIRFLOW_UID:-50000}:0"
    command: ["bash", "-c", "airflow scheduler"]
    restart: on-failure

  airflow-worker:
    image: apache/airflow:3.1.5
    container_name: airflow-worker
    networks:
      - app-network
    depends_on:
      airflow-api-server:
        condition: service_started
    environment: *airflow-env
    volumes: *airflow-vols
    user: "${AIRFLOW_UID:-50000}:0"
    command: ["bash", "-c", "airflow celery worker"]
    restart: on-failure

  airflow-triggerer:
    image: apache/airflow:3.1.5
    container_name: airflow-triggerer
    networks:
      - app-network
    depends_on:
      airflow-api-server:
        condition: service_started
    environment: *airflow-env
    volumes: *airflow-vols
    user: "${AIRFLOW_UID:-50000}:0"
    command: ["bash", "-c", "airflow triggerer"]
    restart: on-failure

  airflow-dag-processor:
    image: apache/airflow:3.1.5
    container_name: airflow-dag-processor
    networks:
      - app-network
    depends_on:
      airflow-api-server:
        condition: service_started
    environment: *airflow-env
    volumes: *airflow-vols
    user: "${AIRFLOW_UID:-50000}:0"
    command: ["bash", "-c", "airflow dag-processor"]
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
  minio-data:
